name: Android Emulator with Docker and ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 6080:6080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Android Emulator in Docker
        run: |
          docker run -d \
            -p 6080:6080 \
            -e EMULATOR_DEVICE="Samsung Galaxy S10" \
            -e WEB_VNC=true \
            --device /dev/kvm \
            --name android-container \
            budtmo/docker-android:emulator_11.0

      - name: Install ngrok v3
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Authenticate ngrok with your token
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start ngrok to forward port 6080
        run: |
          nohup ngrok http 6080 > ngrok.log &

      - name: Wait for Emulator to start
        run: |
          sleep 60

      - name: Get ngrok public URL
        run: |
          sleep 10
          curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url
          sleep 3600

      - name: Run tests (optional)
        run: |
          echo "Running Android tests..."
